### ISSUE TITLE
как его запустить?)

### ISSUE THREAD

**Issue by freddicruger** [Antonkoch999/mvp_budgeting_telegram_bot_aiogram#1]
.env все прописал.
pip install -r req...txt установил
да я даже в тестовом окружение все это делаю
но почему я не могу запустить его..
/
Traceback (most recent call last):
  File "/mvp_budgeting_telegram_bot_aiogram/aiogram_modul/bot.py", line 9, in <module>
    from aiogram_modul.constants import MENU_COMMANDS
ModuleNotFoundError: No module named 'aiogram_modul'
/

куда мне прописать чтобы он видел эти чертовы локальные модули...

**Comment by Antonkoch999** [comment]
Он вообще не для общего использования) 
но в целом как я понимаю тебе может помочь прописать в консоле это: 
export PYTHONPATH="${PYTHONPATH}:/path_to/mvp_budgeting_telegram_bot_aiogram"

**Comment by Antonkoch999** [comment]
перенес файл с запуском в корневой модуль и переименовал его. пробуй запускать
